[package]
name = "olympia-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
olympia_core = {path = "../olympia-core"}
clap ={ version = "4.5.37", features = ["derive"] }
log = "0.4.27"
env_logger = "0.11.8"
